version: '3.6'

services:
  blogapp:
    container_name: blogapp
    build:
      context: ./blogapp/.
    ports:
      - 8000:8000
    env_file:
      - blogapp/.env
    environment:
      - DB_HOST=postgresdb
    volumes:
      - ./blogapp/app:/home/blogapp/app
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: